### ISSUE TITLE
Python bindings segfault

### ISSUE THREAD

**Issue by lukasm91** [MeteoSwiss-APN/dawn#250]
Python bindings segfault with recent version of python, e.g. with python 3.6.5 (e.g. on dom) and python 3.7.4. 

```
 > PYTHONPATH=/home/lukas/documents/work/dawn/install/python/ python install/examples/python/copy_stencil.py 
Segmentation fault (core dumped)
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5685132 in dawn::util::toOptionsWrapper (options=0x557726d0) at /home/lukas/documents/work/dawn/src/dawn-c/util/OptionsWrapper.h:241
241       if(!options->Impl)
(gdb) bt
#0  0x00007ffff5685132 in dawn::util::toOptionsWrapper (options=0x557726d0) at /home/lukas/documents/work/dawn/src/dawn-c/util/OptionsWrapper.h:241
#1  0x00007ffff56830fd in dawnOptionsSet (options=0x557726d0, name=0x7ffff751b170 "Backend", value=0x558fb060) at /home/lukas/documents/work/dawn/src/dawn-c/Options.cpp:97
```
It looks like the pointer is broken when returned to python and passed to C++ again.

**Comment by havogt** [comment]
The issue is incorrect use of the ctypes library. If you don't specify the arguments type and the return type, it will assume `int`. Therefore 64 bit pointers will get truncated. A fix would be to add something like the following to all dawnC calls:
```
dawn.dawnOptionsCreate.restype = c_void_p
```
or
```
 dawn.dawnOptionsSet.argtypes = [
     ctypes.c_void_p,
     ctypes.c_char_p,
     ctypes.c_void_p
 ]
```
